// GENERATED by 'npm run sim:ratings' — do not edit by hand.
// Bradley–Terry Elo across the rated bot versions, anchored so
// claude-v2 = 0 (the permanent field-floor anchor). Only RELATIVE gaps are
// meaningful; the friendly display offset lives in roles.ts (ratingFor).
// Regenerate whenever a version is added (or to refresh the whole ladder).

export const RATING_ANCHOR = "claude-v2";

export const BOT_RATINGS: Readonly<Partial<Record<string, number>>> = {
  "fable-v10": 152.7,
  "fable-v8": 150.6,
  "fable-v7": 150.0,
  "fable-v6": 142.4,
  "fable-v2": 142.4,
  "fable-v5": 142.3,
  "fable-v9": 138.1,
  "fable-v3": 137.3,
  "fable-v4": 136.1,
  "claude-v46": 133.3,
  "fable-v1": 120.2,
  "claude-v45": 111.4,
  "claude-v47": 91.8,
  "opt-v4": 66.0,
  "claude-v41": 64.4,
  "opt-v2": 62.7,
  "claude-v38": 58.2,
  "claude-v36": 45.4,
  "jane-v4": 32.8,
  "jane-v2": 24.3,
  "claude-v2": 0.0,
  "claude-v35": -13.4,
  "claude-v17": -31.9,
  "claude-v5": -38.9,
  "trade-v1": -105.7,
  "kyle-v1": -3667.5,
};
