// GENERATED by 'npm run sim:ratings' — do not edit by hand.
// Bradley–Terry Elo across the lobby-fieldable bot versions, anchored so
// claude-v2 = 0 (the permanent field-floor anchor). Only RELATIVE gaps are
// meaningful; the friendly display offset lives in roles.ts (ratingFor).
// Regenerate when a lobby pointer moves or a rated version is added.

export const RATING_ANCHOR = "claude-v2";

export const BOT_RATINGS: Readonly<Partial<Record<string, number>>> = {
  "jane-v4": 114.8,
  "jane-v2": 100.8,
  "jane-v1": 69.8,
  "claude-v35": 65.2,
  "claude-v2": 0.0,
  "gemini-v1": -154.1,
};
