// GENERATED by 'npm run sim:ratings' — do not edit by hand.
// Bradley–Terry Elo across the rated bot versions, anchored so
// claude-v2 = 0 (the permanent field-floor anchor). Only RELATIVE gaps are
// meaningful; the friendly display offset lives in roles.ts (ratingFor).
// Regenerate whenever a version is added (or to refresh the whole ladder).

export const RATING_ANCHOR = "claude-v2";

export const BOT_RATINGS: Readonly<Partial<Record<string, number>>> = {
  "fable-v11": 151.7,
  "fable-v10": 149.6,
  "fable-v8": 148.2,
  "fable-v7": 146.1,
  "fable-v2": 139.3,
  "fable-v5": 139.2,
  "fable-v6": 138.4,
  "fable-v9": 135.0,
  "fable-v3": 134.2,
  "fable-v4": 133.0,
  "claude-v46": 130.2,
  "fable-v1": 118.3,
  "claude-v45": 106.5,
  "claude-v47": 88.8,
  "opt-v4": 61.1,
  "claude-v41": 60.0,
  "opt-v2": 58.8,
  "claude-v38": 55.1,
  "claude-v36": 42.9,
  "jane-v4": 29.4,
  "jane-v2": 21.5,
  "claude-v2": 0.0,
  "claude-v35": -15.5,
  "claude-v17": -34.6,
  "claude-v5": -40.8,
  "trade-v1": -108.7,
  "kyle-v1": -3662.0,
};
