import { writeFileSync } from "node:fs";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { fitElo, type PairResult } from "./elo";
import { defaultWorkerCount, pairingSpecs, WorkerPool } from "./parallel";
import { BOT_ROLES } from "./roles";
import { VERSIONS } from "./versions";

// ---------------------------------------------------------------------------
// `npm run sim:ratings` — produce the lobby's strength ladder and write it to
// `bots/ratings.ts` (a GENERATED data file; never hand-edit it). For every
// version the lobby can field (each pointer in BOT_ROLES) plus the fixed ANCHOR,
// play a full round-robin and fit one Bradley–Terry Elo across them. The lobby
// shows these numbers so a player can compare bots at a glance — only the RELATIVE
// gaps carry meaning (see `bots/CLAUDE.md` "Lobby strength ratings").
//
// WHY a fixed anchor: Elo is only defined up to a global offset, so we pin one
// version to 0. We pin `claude-v2` (the field floor) FOREVER — never the moving
// champion/base — so a saved number stays comparable across regenerations and
// over time. Raising the competitive field floor later doesn't require moving the
// anchor; it can sit out competition and still define the scale. The display
// offset that turns 0 into a friendly baseline lives in `roles.ts`, not here —
// this file stays the raw measurement.
//
// Regenerate whenever a pointer moves or a new rated version appears (it's the
// data half of surfacing strength, the analog of the gauntlet's EVOLUTION row).
// Deterministic by seed: same versions + seeds reproduce the same ladder.
// ---------------------------------------------------------------------------

/** Pinned to 0 Elo, permanently — the field floor. Do not change without
 *  regenerating every number against the new anchor (a re-anchor is just a
 *  constant shift, so prefer keeping this stable). */
const ANCHOR = "claude-v2";

interface Args {
  versions: string[];
  games: number;
  maxTurns: number;
  workers: number;
  prefix: string;
}

function num(argv: readonly string[], i: number, fallback: number): number {
  const n = Number(argv[i]);
  return Number.isNaN(n) ? fallback : n;
}

function parseArgs(argv: readonly string[]): Args {
  const a: Args = {
    versions: [],
    games: 400,
    maxTurns: 2000,
    workers: defaultWorkerCount(),
    prefix: "ratings",
  };
  const explicit: string[] = [];
  let all = false;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--games") a.games = num(argv, ++i, a.games);
    else if (arg === "--turns") a.maxTurns = num(argv, ++i, a.maxTurns);
    else if (arg === "--workers") a.workers = num(argv, ++i, a.workers);
    else if (arg === "--prefix") a.prefix = argv[++i];
    else if (arg === "--all") all = true;
    else if (arg.startsWith("--")) throw new Error(`unknown flag "${arg}"`);
    else explicit.push(arg);
  }

  // Default set: the ANCHOR plus every distinct version any lobby pointer
  // resolves to — the only versions a player can actually pick, so the only ones
  // worth a displayed rating. `--all` rates the whole archive (a fuller ladder);
  // an explicit list overrides both.
  const lobby = [...new Set(BOT_ROLES.map((r) => r.version))];
  const allVersions = Object.keys(VERSIONS).filter((v) => v !== "dumb");
  const chosen =
    explicit.length > 0 ? explicit : all ? allVersions : [ANCHOR, ...lobby];
  a.versions = [...new Set([ANCHOR, ...chosen])];
  return a;
}

/** Play a fixed round-robin pairing and tally decisive results (draws ignored). */
async function pairing(
  pool: WorkerPool,
  a: string,
  b: string,
  prefix: string,
  games: number,
  maxTurns: number,
): Promise<PairResult> {
  const specs = pairingSpecs(a, b, `${prefix}:${a}-vs-${b}`, 0, games, maxTurns);
  const results = await pool.run(specs);
  let aWins = 0;
  let bWins = 0;
  for (const r of results) {
    if (r.error !== undefined) continue;
    if (r.winnerLabel === a) aWins++;
    else if (r.winnerLabel === b) bWins++;
  }
  return { a, b, aWins, bWins };
}

function renderFile(anchor: string, elo: Record<string, number>): string {
  const sorted = Object.keys(elo).sort((x, y) => elo[y] - elo[x]);
  const body = sorted.map((v) => `  ${JSON.stringify(v)}: ${elo[v].toFixed(1)},`).join("\n");
  return [
    "// GENERATED by 'npm run sim:ratings' — do not edit by hand.",
    "// Bradley–Terry Elo across the lobby-fieldable bot versions, anchored so",
    `// ${anchor} = 0 (the permanent field-floor anchor). Only RELATIVE gaps are`,
    "// meaningful; the friendly display offset lives in roles.ts (ratingFor).",
    "// Regenerate when a lobby pointer moves or a rated version is added.",
    "",
    `export const RATING_ANCHOR = ${JSON.stringify(anchor)};`,
    "",
    "export const BOT_RATINGS: Readonly<Partial<Record<string, number>>> = {",
    body,
    "};",
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));

  const known = Object.keys(VERSIONS);
  for (const v of args.versions) {
    if (!known.includes(v)) throw new Error(`unknown version "${v}" (known: ${known.join(", ")})`);
    if (v === "dumb") throw new Error("`dumb` is a null bot and cannot be rated");
  }
  if (!args.versions.includes(ANCHOR)) {
    throw new Error(`the anchor "${ANCHOR}" must be in the rated set`);
  }
  if (args.versions.length < 2) throw new Error("need at least two versions to rate");

  const pairs = (args.versions.length * (args.versions.length - 1)) / 2;
  console.log(
    `\nMonopoly — ratings ladder\n` +
      `Versions (${args.versions.length}): [${args.versions.join(", ")}]\n` +
      `Anchor: ${ANCHOR} = 0   Round-robin: ${pairs} pairings × ${args.games} games\n` +
      `Seeds: "${args.prefix}:*"   Workers: ${args.workers}   Max turns: ${args.maxTurns}\n`,
  );

  const pool = new WorkerPool(args.workers);
  const start = process.hrtime.bigint();
  try {
    const results: PairResult[] = [];
    let done = 0;
    for (let i = 0; i < args.versions.length; i++) {
      for (let j = i + 1; j < args.versions.length; j++) {
        const res = await pairing(
          pool,
          args.versions[i],
          args.versions[j],
          args.prefix,
          args.games,
          args.maxTurns,
        );
        results.push(res);
        done++;
        process.stderr.write(
          `\r  ${done}/${pairs} pairings  (${res.a} ${res.aWins}–${res.bWins} ${res.b})`.padEnd(60),
        );
      }
    }
    process.stderr.write("\n");

    const elo = fitElo(args.versions, results, { anchor: ANCHOR });
    const outPath = fileURLToPath(new URL("./ratings.ts", import.meta.url));
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- `outPath` is this script's own directory joined with the hardcoded filename "ratings.ts"; there is no external/user input, so the path-injection this rule guards against cannot occur.
    writeFileSync(outPath, renderFile(ANCHOR, elo));

    const secs = Number(process.hrtime.bigint() - start) / 1e9;
    const ladder = Object.entries(elo)
      .sort((a, b) => b[1] - a[1])
      .map(([l, e]) => `    ${l.padEnd(12)} ${e >= 0 ? "+" : ""}${e.toFixed(1)}`)
      .join("\n");
    console.log(`\n  Elo ladder (${ANCHOR} = 0):\n${ladder}\n`);
    console.log(`  Wrote ${outPath}`);
    console.log(`\n  (${secs.toFixed(1)}s on ${pool.size} workers)\n`);
  } finally {
    await pool.close();
  }
}

main().catch((e: unknown) => {
  console.error((e as Error).message);
  process.exit(1);
});
